name: first workflow
on:
  push:
    branches:
      - "main"
jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: before checkout action
        run: ls
        shell: bash

      - name: checkout steps
        uses: actions/checkout
        
      - name: after checkout action
        run: ls
        shell: bash